export const TopMenuData = [
  {
    label: "여성의류",
    href: "1",
    categories: [
      {
        label: "티셔츠",
        href: "11",
        categories: [
          { label: "반팔", href: "27" },
          { label: "긴팔", href: "28" },
          { label: "슬리브리스", href: "29" },
          { label: "스웻/맨투맨", href: "30" },
          { label: "플리츠", href: "31" },
        ],
      },
      { label: "가디건", href: "12" },
      {
        label: "니트/스웨터",
        href: "13",
        categories: [
          { label: "코튼", href: "32" },
          { label: "린넨", href: "33" },
          { label: "긴팔", href: "34" },
          { label: "반팔", href: "35" },
          { label: "베스트", href: "36" },
          { label: "슬리브리스", href: "37" },
          { label: "라운드넥", href: "38" },
          { label: "브이넥", href: "39" },
          { label: "울/캐시미어", href: "40" },
          { label: "터틀넥", href: "41" },
        ],
      },
      {
        label: "원피스",
        href: "14",
        categories: [
          { label: "데님 원피스", href: "42" },
          { label: "코튼", href: "43" },
          { label: "린넨", href: "44" },
          { label: "쉬폰/실크", href: "45" },
          { label: "롱/맥시", href: "46" },
          { label: "미디", href: "47" },
          { label: "미니", href: "48" },
          { label: "긴팔", href: "49" },
          { label: "반팔", href: "50" },
          { label: "슬리브리스", href: "51" },
          { label: "점프수트", href: "52" },
        ],
      },
      {
        label: "팬츠",
        href: "15",
        categories: [
          { label: "데님", href: "53" },
          { label: "슬랙스", href: "54" },
          { label: "면팬츠", href: "55" },
          { label: "트레이닝/조거", href: "56" },
          { label: "롱", href: "57" },
          { label: "하프(5~7부)", href: "58" },
          { label: "숏츠", href: "59" },
          { label: "와이드", href: "60" },
          { label: "부츠컷", href: "61" },
          { label: "스트레이트", href: "62" },
          { label: "배기", href: "63" },
          { label: "슬림", href: "64" },
          { label: "레깅스", href: "65" },
        ],
      },
      {
        label: "데님팬츠",
        href: "16",
        categories: [
          { label: "롱", href: "66" },
          { label: "와이드", href: "67" },
          { label: "부츠컷", href: "68" },
          { label: "보이프렌드/배기", href: "69" },
          { label: "스트레이트", href: "70" },
          { label: "숏", href: "71" },
        ],
      },
      {
        label: "블라우스",
        href: "17",
        categories: [
          { label: "긴팔", href: "72" },
          { label: "반팔", href: "73" },
          { label: "슬리브리스", href: "74" },
          { label: "카라", href: "75" },
          { label: "헨리넥", href: "76" },
          { label: "코튼", href: "77" },
          { label: "린넨", href: "78" },
          { label: "쉬폰/실크", href: "79" },
        ],
      },
      {
        label: "셔츠",
        href: "18",
        categories: [
          { label: "리넨", href: "80" },
          { label: "데님", href: "81" },
          { label: "스트라이프", href: "82" },
          { label: "체크", href: "83" },
          { label: "크롭", href: "84" },
          { label: "긴팔", href: "85" },
          { label: "반팔", href: "86" },
          { label: "울/캐시미어", href: "87" },
        ],
      },
      {
        label: "스커트",
        href: "19",
        categories: [
          { label: "플리츠/플레어", href: "88" },
          { label: "H라인", href: "89" },
          { label: "A라인", href: "90" },
          { label: "데님", href: "91" },
          { label: "레더", href: "92" },
          { label: "롱 스커트", href: "93" },
          { label: "미디스커트", href: "94" },
          { label: "미니스커트", href: "95" },
        ],
      },
      {
        label: "자켓",
        href: "20",
        categories: [
          { label: "블레이저", href: "96" },
          { label: "트위드자켓", href: "97" },
          { label: "반팔 자켓", href: "98" },
          { label: "리넨 자켓", href: "99" },
          { label: "레더자켓", href: "100" },
          { label: "퀄팅자켓", href: "101" },
          { label: "플리스자켓", href: "102" },
        ],
      },
      {
        label: "점퍼/베스트",
        href: "21",
        categories: [
          { label: "바람막이", href: "103" },
          { label: "후드집업", href: "104" },
          { label: "베스트", href: "105" },
          { label: "블루종", href: "106" },
          { label: "야상", href: "107" },
          { label: "다운/패딩", href: "108" },
        ],
      },
      {
        label: "코트",
        href: "22",
        categories: [
          { label: "트렌치코트", href: "109" },
          { label: "하프코트", href: "110" },
          { label: "롱코트", href: "111" },
          { label: "울/캐시미어", href: "112" },
          { label: "레더", href: "113" },
        ],
      },
      {
        label: "퍼/레더",
        href: "23",
        categories: [
          { label: "레더아우터", href: "114" },
          { label: "레더팬츠/스커트", href: "115" },
          { label: "무스탕/밍크", href: "116" },
        ],
      },
      {
        label: "언더웨어",
        href: "24",
        categories: [{ label: "브라", href: "117" }],
      },
      {
        label: "스윔웨어",
        href: "25",
        categories: [
          { label: "비키니수영복", href: "118" },
          { label: "원피스수영복", href: "119" },
          { label: "비치웨어", href: "120" },
        ],
      },
      {
        label: "유니섹스",
        href: "26",
        categories: [{ label: "점퍼", href: "121" }],
      },
    ],
  },
  {
    label: "남성의류",
    href: "2",
    categories: [
      {
        label: "티셔츠",
        href: "122",
        categories: [
          { label: "반팔", href: "135" },
          { label: "긴팔", href: "136" },
          { label: "카라", href: "137" },
          { label: "스웻/맨투맨", href: "138" },
          { label: "후드", href: "139" },
          { label: "민소매", href: "140" },
        ],
      },
      {
        label: "팬츠",
        href: "123",
        categories: [
          { label: "롱", href: "141" },
          { label: "숏/하프(5~7부)", href: "142" },
          { label: "슬랙스", href: "143" },
          { label: "데님", href: "144" },
          { label: "치노", href: "145" },
          { label: "면", href: "146" },
          { label: "모직", href: "147" },
          { label: "슬림/스트레이트", href: "148" },
          { label: "와이드", href: "149" },
          { label: "조거 밴딩", href: "150" },
        ],
      },
      {
        label: "데님팬츠",
        href: "124",
        categories: [
          { label: "롱", href: "151" },
          { label: "스트레이트", href: "152" },
          { label: "와이드", href: "153" },
          { label: "숏", href: "154" },
        ],
      },
      {
        label: "셔츠",
        href: "125",
        categories: [
          { label: "긴팔", href: "155" },
          { label: "반팔", href: "156" },
          { label: "린넨", href: "157" },
          { label: "솔리드", href: "158" },
          { label: "체크", href: "159" },
          { label: "드레스셔츠", href: "160" },
        ],
      },
      {
        label: "점퍼",
        href: "126",
        categories: [
          { label: "캐주얼 점퍼", href: "161" },
          { label: "바람막이", href: "162" },
          { label: "야상/사파리", href: "163" },
          { label: "가죽", href: "164" },
          { label: "다운/패딩", href: "165" },
          { label: "무스탕", href: "166" },
        ],
      },
      {
        label: "니트/스웨터",
        href: "127",
        categories: [
          { label: "라운드넥", href: "167" },
          { label: "카라넥", href: "168" },
          { label: "브이넥", href: "169" },
        ],
      },
      {
        label: "자켓/베스트",
        href: "128",
        categories: [
          { label: "숏/하프 자켓", href: "170" },
          { label: "롱 자켓", href: "171" },
          { label: "베스트", href: "172" },
          { label: "퀄팅자켓", href: "173" },
        ],
      },
      {
        label: "코트",
        href: "129",
        categories: [
          { label: "트렌치", href: "174" },
          { label: "롱", href: "175" },
          { label: "하프", href: "176" },
          { label: "울/캐시미어", href: "177" },
        ],
      },
      { label: "가디건", href: "130" },
      {
        label: "수트/정장",
        href: "131",
        categories: [
          { label: "정장세트", href: "178" },
          { label: "정장상의", href: "179" },
          { label: "정장하의", href: "180" },
        ],
      },
      { label: "유니섹스", href: "132" },
      { label: "언더웨어", href: "133" },
      { label: "스윔웨어", href: "134" },
    ],
  },
  {
    label: "가방/잡화",
    href: "3",
    categories: [
      {
        label: "여성가방",
        href: "181",
        categories: [
          { label: "토트백", href: "198" },
          { label: "숄더백", href: "199" },
          { label: "크로스백", href: "200" },
          { label: "백팩", href: "201" },
          { label: "캔버스/에코백", href: "202" },
          { label: "보스톤백", href: "203" },
          { label: "슬링백", href: "204" },
          { label: "클러치/파우치", href: "205" },
          { label: "여행가방", href: "206" },
        ],
      },
      {
        label: "여성지갑",
        href: "182",
        categories: [
          { label: "반지갑", href: "207" },
          { label: "중지갑", href: "208" },
          { label: "장지갑", href: "209" },
          { label: "명함/카드지갑", href: "210" },
          { label: "동전지갑", href: "211" },
          { label: "머니클립", href: "212" },
          { label: "여권지갑", href: "213" },
        ],
      },
      {
        label: "남성가방",
        href: "183",
        categories: [
          { label: "토트백/숄더백", href: "214" },
          { label: "크로스백", href: "215" },
          { label: "백팩", href: "216" },
          { label: "슬링백", href: "217" },
          { label: "캔버스/에코백", href: "218" },
          { label: "보스톤백", href: "219" },
          { label: "서류가방", href: "220" },
          { label: "클러치백", href: "221" },
          { label: "여행가방", href: "222" },
        ],
      },
      {
        label: "남성지갑",
        href: "184",
        categories: [
          { label: "반지갑", href: "223" },
          { label: "중지갑", href: "224" },
          { label: "장지갑", href: "225" },
          { label: "명함/카드지갑", href: "226" },
          { label: "머니클립", href: "227" },
          { label: "여권지갑", href: "228" },
        ],
      },
      { label: "벨트", href: "185" },
      {
        label: "스카프/머플러",
        href: "186",
        categories: [
          { label: "스카프", href: "229" },
          { label: "머플러", href: "230" },
        ],
      },
      {
        label: "모자",
        href: "187",
        categories: [
          { label: "야구모자", href: "231" },
          { label: "썬캡", href: "232" },
          { label: "스냅백", href: "233" },
          { label: "군모/헌팅캡", href: "234" },
          { label: "비니", href: "235" },
          { label: "버킷햇", href: "236" },
        ],
      },
      {
        label: "양말/스타킹",
        href: "188",
        categories: [
          { label: "양말", href: "237" },
          { label: "스타킹", href: "238" },
          { label: "양말세트", href: "239" },
        ],
      },
      { label: "헤어ACC", href: "189" },
      {
        label: "우산/양산",
        href: "190",
        categories: [
          { label: "양산", href: "240" },
          { label: "우산", href: "241" },
        ],
      },
      {
        label: "시계/주얼리",
        href: "191",
        categories: [
          { label: "프리미엄시계", href: "242" },
          { label: "패션시계", href: "243" },
          { label: "시계 소품", href: "244" },
          { label: "명품주얼리", href: "245" },
          { label: "브랜드주얼리", href: "246" },
          { label: "순금/실버", href: "247" },
        ],
      },
      { label: "키링/키홀더", href: "192" },
      { label: "아이웨어", href: "193" },
      { label: "핸드폰케이스", href: "194" },
      {
        label: "장갑/워머",
        href: "195",
        categories: [
          { label: "장갑", href: "248" },
          { label: "워머", href: "249" },
        ],
      },
      { label: "넥타이", href: "196" },
      {
        label: "기타ACC",
        href: "197",
        categories: [
          { label: "손수건", href: "250" },
          { label: "와펜", href: "251" },
          { label: "기타소품", href: "252" },
          { label: "커프스", href: "253" },
          { label: "귀마개", href: "254" },
          { label: "깔창", href: "255" },
          { label: "멜빵/서스펜더", href: "256" },
          { label: "IT소품", href: "257" },
        ],
      },
    ],
  },
  {
    label: "슈즈",
    href: "4",
    categories: [
      { label: "여성 샌들", href: "258" },
      { label: "여성 슬리퍼", href: "259" },
      { label: "여성 플랫/로퍼", href: "260" },
      { label: "여성 블로퍼/뮬", href: "261" },
      { label: "여성 스니커즈", href: "262" },
      { label: "여성 펌프스/힐", href: "263" },
      { label: "여성 등산/골프화", href: "264" },
      { label: "여성 부츠", href: "265" },
      { label: "남성 샌들", href: "266" },
      { label: "남성 슬리퍼", href: "267" },
      { label: "남성 스니커즈", href: "268" },
      { label: "남성 구두", href: "269" },
      { label: "남성 등산/골프화", href: "270" },
      { label: "남성 부츠", href: "271" },
      { label: "스포츠화", href: "272" },
      { label: "아동화", href: "273" },
    ],
  },
  {
    label: "골프",
    href: "5",
    categories: [
      { label: "여성골프 웨어", href: "274" },
      { label: "남성골프 웨어", href: "275" },
      { label: "골프모자", href: "276" },
      { label: "골프백", href: "277" },
      { label: "골프장갑", href: "278" },
      { label: "골프양말", href: "279" },
      { label: "골프벨트", href: "280" },
      { label: "골프ACC", href: "281" },
      { label: "골프클럽", href: "282" },
      { label: "골프화", href: "283" },
      { label: "골프공", href: "284" },
      { label: "필드/연습용품", href: "285" },
      { label: "거리측정기", href: "286" },
      { label: "파크골프", href: "287" },
    ],
  },
  {
    label: "스포츠/레져",
    href: "6",
    categories: [
      { label: "여성스포츠 웨어", href: "288" },
      { label: "남성스포츠 웨어", href: "289" },
      { label: "아동스포츠 웨어", href: "290" },
      { label: "스포츠슈즈", href: "291" },
      { label: "스포츠용품", href: "292" },
      { label: "수상스포츠", href: "293" },
      { label: "캠핑", href: "294" },
      { label: "아웃도어", href: "295" },
      { label: "헬스/요가", href: "296" },
      { label: "스키/보드", href: "297" },
      { label: "낚시", href: "298" },
    ],
  },
  {
    label: "명품",
    href: "7",
    categories: [
      { label: "여성가방", href: "299" },
      { label: "여성슈즈", href: "300" },
      { label: "여성의류", href: "301" },
      { label: "여성지갑/벨트", href: "302" },
      { label: "남성가방", href: "303" },
      { label: "남성슈즈", href: "304" },
      { label: "남성의류", href: "305" },
      { label: "남성지갑/벨트", href: "306" },
      { label: "아이웨어", href: "307" },
      { label: "ACC", href: "308" },
      { label: "시계", href: "309" },
      { label: "주얼리", href: "310" },
      { label: "여행가방", href: "311" },
      { label: "키즈", href: "312" },
      { label: "중고명품", href: "313" },
    ],
  },
  {
    label: "리빙",
    href: "8",
    categories: [
      { label: "패브릭/침구", href: "314" },
      { label: "가구/홈데코", href: "315" },
      { label: "주방", href: "316" },
      { label: "수납/생활", href: "317" },
      { label: "가전", href: "318" },
      { label: "식품", href: "319" },
      { label: "반려동물", href: "320" },
    ],
  },
  {
    label: "뷰티",
    href: "9",
    categories: [
      { label: "향수", href: "321" },
      { label: "스킨케어", href: "322" },
      { label: "메이크업", href: "323" },
      { label: "헤어케어", href: "324" },
      { label: "명품화장품", href: "325" },
      { label: "남성케어", href: "326" },
      { label: "미백/탄력", href: "327" },
      { label: "비건/클린", href: "328" },
      { label: "바디케어", href: "329" },
      { label: "베이비/키즈", href: "330" },
      { label: "네일케어", href: "331" },
      { label: "미용기기/소품", href: "332" },
      { label: "이너뷰티", href: "333" },
    ],
  },
  {
    label: "키즈",
    href: "10",
    categories: [
      { label: "베이비 패션", href: "334" },
      { label: "키즈/주니어패션", href: "335" },
      { label: "가방/잡화", href: "336" },
      { label: "슈즈", href: "337" },
      { label: "출산/유아용품/기저귀", href: "338" },
      { label: "실내용품/가구", href: "339" },
      { label: "완구/교구/도서", href: "340" },
    ],
  },
];
